name: JW
title: JW | 기억과 공유
description: 기억과 공유
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: jw2471358@gmail.com
disqus_username: James
show_hero: false
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
paginate: 5